name: Discord Bot CI

on:
  push:
    branches:
      - main
    paths:
      - "discord-bot/**"

env:
  # GHCR image name format: ghcr.io/<owner>/<repo>/<image_name>
  # Replace <owner> with your GitHub username or organization name
  # Replace <repo> with your GitHub repository name
  # Example: ghcr.io/your-github-username/minecraft-server/minecraft-discord-bot
  GHCR_IMAGE_NAME: ghcr.io/${{ github.repository }}/minecraft-discord-bot

jobs:
  build-and-push:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write # Required to push to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./discord-bot
          platforms: linux/arm64
          push: true
          tags: ${{ env.GHCR_IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
